version: 2.1

orbs:
  ssh-tunnel: symbol/ssh-tunnel@1.1.0

executors:
  node:
    docker:
      - image: circleci/node:14.17
jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  deploy-staging:
    executor: node
    working_directory: ~/repo
    description: "Deploy over SSH"
    steps:
      - add_ssh_keys:
          fingerprints:
            - '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
      - checkout
      - ssh-tunnel/setup:
          key_fingerprint: '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
          timeout: 20000,
          from_host: '3.142.187.92'
          from_port: '31231'
          to_host: 'ec2-54-91-178-219.compute-1.amazonaws.com'
          to_port: '22'
      - run: sh /home/ubuntu/react-app/restart-app.sh

workflows:
  version: 2
  main:
    jobs:
      - deploy-staging:
          name: deploy-staging
          context: react-app-staging
          filters:
            branches:
              only:
                - circleci-project-setup
