version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.17
jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
  deploy-staging:
    executor: node
    working_directory: ~/repo
    description: "Deploy over SSH"
    steps:
      - add_ssh_keys:
          fingerprints:
            - '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
      #- run: |
      #    ssh -o "StrictHostKeyChecking no" -4 -L 8443:ec2-54-91-178-219.compute-1.amazonaws.com:22 -Nf ubuntu@3.142.187.92 -p 31231 
      #    ssh-keyscan -p 8443 localhost >> ~/.ssh/known_hosts  #not required if you also trust the both server’s keys explicitly
      #    ssh ubuntu@localhost -p 8443 'whoami && hostname'
      # - run: ssh -L 3.142.187.92:31231:ec2-54-91-178-219.compute-1.amazonaws.com:22 -oStrictHostKeyChecking=no -4 -N -q ubuntu@3.142.187.92 -p 31231
      # - run: ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -J ubuntu@3.142.187.92:31231 ubuntu@ec2-54-91-178-219.compute-1.amazonaws.com
      # - run: ssh -o "StrictHostKeyChecking no" -4 -L 8443:ec2-54-91-178-219.compute-1.amazonaws.com:22 -Nf ubuntu@3.142.187.92 -p 31231 
      - run: |
        ssh-keyscan -p 22 ec2-54-91-178-219.compute-1.amazonaws.com >> ~/.ssh/known_hosts  #not required if you also trust the both server’s keys explicitly
        ssh -o ProxyCommand="ssh -o 'StrictHostKeyChecking no' -W %h:%p ubuntu@3.142.187.92 -p 31231" ubuntu@ec2-54-91-178-219.compute-1.amazonaws.com 
        pwd
      

workflows:
  version: 2
  main:
    jobs:
      - deploy-staging:
          name: deploy-staging
          context: react-app-staging
          filters:
            branches:
              only:
                - circleci-project-setup
