version: 2.1

orbs:
  dmz: eddiewebb/dmz@0.0.7

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  deploy-staging:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
      - run:
          name: Update known hosts
          command: ssh-keyscan -H 3.142.187.92 >> ~/.ssh/known_hosts
      - dmz/open_tunnel:
          local_port: "31231"
          target_host: "ec2-54-91-178-219.compute-1.amazonaws.com"
          target_port: "22"
          bastion_user: ubuntu
          bastion_host: 3.142.187.92
      - run:
          name: Test Deploy over SSH
          command: ssh -o "StrictHostKeyChecking no" ubuntu@ec2-54-91-178-219.compute-1.amazonaws.com "sh /home/ubuntu/react-app/restart-app.sh"

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: build-pr
          context: react-app-staging
          filters:
            branches:
              only:
                - circleci-project-setup

      - deploy-staging:
          name: deploy-staging
          context: react-app-staging
          requires:
            - build-pr
          filters:
            branches:
              only:
                - circleci-project-setup
