version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.17

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn build

  deploy:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '6b:9d:f0:24:b7:f4:df:69:46:a3:36:c3:6a:1f:ef:c4'
      - run:
          name: Deploy over SSH
          command: ssh -o "StrictHostKeyChecking no" ubuntu@$SERVER_IP "sh /home/ubuntu/react-app/restart-app.sh"

  deploy-staging:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '43:ce:13:51:63:18:f9:ba:13:1c:5d:61:02:89:c7:37'
      - run:
          name: Deploy Staging over SSH
          command: ssh -o "StrictHostKeyChecking no" ubuntu@3.218.67.255 "sh /home/ubuntu/react-app/restart-app.sh"

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: build-pr
          context: explorer-backend-staging
          filters:
            branches:
              only:
                - circleci-project-setup

      - deploy-staging:
          name: deploy-staging
          context: explorer-backend-staging
          requires:
            - build-pr
          filters:
            branches:
              only:
                - circleci-project-setup
