version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.17

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  deploy-staging:
    executor: node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '07:51:01:ba:d0:49:5d:57:73:2a:2d:c7:aa:7c:cc:3b'
      - run:
          name: Test Deploy over SSH
          command: ssh -o "StrictHostKeyChecking no" -J ubuntu@3.142.187.92 -p 31231 ubuntu@ec2-54-91-178-219.compute-1.amazonaws.com "sh /home/ubuntu/react-app/restart-app.sh"

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: build-pr
          context: react-app-staging
          filters:
            branches:
              only:
                - circleci-project-setup

      - deploy-staging:
          name: deploy-staging
          context: react-app-staging
          requires:
            - build-pr
          filters:
            branches:
              only:
                - circleci-project-setup
